import { Shield } from "lucide-react";
import { Link } from "react-router-dom";

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50">
      <div className="bg-white border-b">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
          <div className="flex items-center gap-3">
            <Link to="/" className="flex items-center gap-3">
              <Shield className="w-8 h-8 text-blue-600" />
              <h1 className="text-2xl font-bold text-gray-900">KidGuard</h1>
            </Link>
          </div>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <h2 className="text-3xl font-bold text-gray-900 mb-2">Privacy Policy</h2>
        <p className="text-sm text-gray-500 mb-8">Last updated: March 26, 2026</p>

        <div className="space-y-8 text-gray-700">
          <section>
            <h3 className="text-xl font-semibold text-gray-900 mb-3">1. Overview</h3>
            <p>
              KidGuard ("we", "our", "us") is a child online safety application designed to help
              parents monitor and protect their children from online grooming on gaming platforms
              such as Roblox. This Privacy Policy explains what data we collect, how we use it,
              and your rights regarding your information.
            </p>
          </section>

          <section>
            <h3 className="text-xl font-semibold text-gray-900 mb-3">2. Data We Collect</h3>
            <ul className="list-disc list-inside space-y-2">
              <li>Parent name, email address, and phone number (provided during registration)</li>
              <li>Child's name (provided by the parent for identification purposes)</li>
              <li>Chat message content flagged as potentially risky by our detection system</li>
              <li>Platform URLs and usernames associated with flagged messages</li>
              <li>Risk scores and detected pattern categories generated by our system</li>
            </ul>
          </section>

          <section>
            <h3 className="text-xl font-semibold text-gray-900 mb-3">3. How We Use Your Data</h3>
            <ul className="list-disc list-inside space-y-2">
              <li>To detect and alert parents about potential online grooming activity</li>
              <li>To send SMS notifications to registered parents when high-risk activity is detected</li>
              <li>To display incident history on the parent dashboard</li>
              <li>To authenticate and manage parent accounts</li>
            </ul>
          </section>

          <section>
            <h3 className="text-xl font-semibold text-gray-900 mb-3">4. Data Sharing</h3>
            <p>
              We do not sell, share, or disclose your personal information to third parties for
              marketing or commercial purposes. Data is only shared with the following service
              providers strictly for operational purposes:
            </p>
            <ul className="list-disc list-inside space-y-2 mt-3">
              <li>
                <strong>Twilio</strong> — used solely to deliver SMS safety alerts to the
                registered parent's phone number
              </li>
              <li>
                <strong>MongoDB</strong> — used to securely store incident and account data
              </li>
            </ul>
          </section>

          <section>
            <h3 className="text-xl font-semibold text-gray-900 mb-3">5. SMS Alerts</h3>
            <p>
              By registering an account and providing your phone number, you consent to receive
              SMS alerts when high-risk activity is detected for your child. You may opt out of
              SMS alerts at any time by replying <strong>STOP</strong> to any message or by
              disabling alerts in your dashboard settings. For help, reply <strong>HELP</strong>.
              Message and data rates may apply.
            </p>
          </section>

          <section>
            <h3 className="text-xl font-semibold text-gray-900 mb-3">6. Data Retention</h3>
            <p>
              Incident data is retained for as long as your account is active. You may request
              deletion of your account and all associated data at any time by contacting us.
            </p>
          </section>

          <section>
            <h3 className="text-xl font-semibold text-gray-900 mb-3">7. Security</h3>
            <p>
              We use industry-standard security practices including password hashing and
              JWT-based authentication to protect your account. All data is stored securely
              and access is restricted to authenticated users only.
            </p>
          </section>

          <section>
            <h3 className="text-xl font-semibold text-gray-900 mb-3">8. Contact</h3>
            <p>
              For privacy-related questions or data deletion requests, contact us at:{" "}
              <a href="mailto:support@kidguard.app" className="text-blue-600 hover:underline">
                support@kidguard.app
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
